# Generated by Django 4.2.5 on 2023-12-11 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_createdat_userprofile_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(1980, 1, 1)),
        ),
    ]
