# Generated by Django 4.1.1 on 2023-11-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobUrl', models.URLField(unique=True)),
                ('site', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('jobType', models.CharField(max_length=255, null=True)),
                ('datePosted', models.DateField(blank=True, null=True)),
                ('interval', models.CharField(max_length=255)),
            ],
        ),
    ]
