# Generated by Django 4.1.1 on 2023-11-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='datePosted',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='jobType',
        ),
    ]
