# Generated by Django 4.2.5 on 2023-12-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobposting_cleaneddescription_jobposting_dateposted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='interval',
        ),
    ]
